config/routes.rb
Rails.application.routes.draw do
  root to: 'site#home'
  
  get 'signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get '/home', to: 'site#home'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: :true
  validates :country, presence: :true

  before_save(:titleize_product)

  scope :three_recent, -> { order(created_at: :desc).limit(3)}

  scope :most_reviewed, -> {(
    select("products.id, products.name, products.country, count(reviews) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

  private
    def titleize_product
      self.name = self.name.titleize
    end
end 

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: :true
  
  validates :content_body, presence: :true
  validates_length_of :content_body, minimum: 50, maximum: 250

  validates :rating, presence: :true
  validates :rating, numericality: { only_integer: true }
  validates :rating, numericality: { greater_than_or_equal_to: 1 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :is_logged_in?
  helper_method :is_admin?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You must be signed in and authorized to make this change."
      redirect_to root_path
    end
  end

  def is_logged_in?
    @current_user.present?
  end

  def is_admin?
    current_user && current_user.admin
  end
end

app/controllers/authorize_controller.rb
class AuthorizeController < ApplicationController
  before_action :authorize, only: [:secret]
  
  def secret
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize, :except => [:show, :index]
  before_action :only => [:edit, :destroy, :create] do
    redirect_to signin_path unless current_user || current_user.admin
    flash[:notice] = "Sorry, that command is only for admins. Please sign in as an admin to continue."
  end

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else 
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, :except => [:show]
  before_action :only => [:edit, :destroy] do
    redirect_to signin_path unless current_user || current_user.admin
    flash[:notice] = "Sorry, that command is only for admins. Please sign in as an admin to continue."
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
      flash[:notice] = "Your review has been successfully added"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit 
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "there was a problem signing up."
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFoodCompany</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container">
      <% if current_user %>
        <%= current_user.email  %> | <%= link_to "Sign Out",  signout_path %>
      <% else %>
        <%= link_to "Sign Up", '/signup' %> | <%= link_to "Sign In", signin_path %>
      <% end %>

      <%= flash[:alert] %>
      <%= flash[:notice] %>
      
      <%= yield %>
      
      <h4>Recent Products</h4>
        <ul>
          <% Product.three_recent.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      <h4>Most Reviewed</h4>
        <ul>
          <% Product.most_reviewed.each do |product| %>
          <li><%=  link_to product.name, product_path(product) %></li>
        <% end %>
        </ul>
      <br>
      <p><%= link_to "Return to products", products_path %></p>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

<% if current_user || current_user.admin %>
  <p><%= link_to "Create new product", new_product_path %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= @product.cost %></h3>

<% if @product.reviews.any? %>
<h4> Here are the reviews for this product:</h4>

<% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<% if current_user || current_user.admin %>
  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete", product_path(@product),
                          :data => {:confirm => "You sure?",
                                    :method => "delete"} %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new Review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Review: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h3><%= @review.content_body %></h3>

<% if current_user || current_user.admin %>
  <p><%= link_to "Edit review", edit_product_review_path(@review) %></p>
  <p><%= link_to "Delete review", product_review_path(@review),
                          :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>
<% end %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/site/home.html.erb
<h1>Mario's Food Products!</h1>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>